<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>MdViewerApp</RootNamespace>
    <AssemblyName>MdViewerApp</AssemblyName>
    <Authors>Keiji Mitsubuchi</Authors>
    <Description>Markdown / SVG viewer (read only)</Description>
    <Copyright>Keiji Mitsubuchi</Copyright>
    <Company>Virtual IP Production</Company>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MdLib\MdLib.csproj" />
    <ProjectReference Include="..\MdWpf\MdWpf.csproj" />
    <ProjectReference Include="..\SvgWpf\SvgWpf.csproj" />
  </ItemGroup>

</Project>
